add_newline = true

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'
symbol = 'AWS:'

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[cmd_duration]
min_time = 1

[gcloud]
format = '[$symbol$account(@$domain)(\($project\))]($style) '
symbol = 'GCP:'

[git_branch]
format = '[$branch]($style) '

[terraform]
format = '[$symbol$workspace]($style) '
symbol = 'TF:'

[time]
format = "[$time]($style) "
time_format = "%Y-%m-%dT%H:%M:%S"
disabled = false

# disabled languages
[golang]
disabled = true
[java]
disabled = true
[package]
disabled = true
[php]
disabled = true
[python]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
[scala]
disabled = true
